/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NewTodo {
        "defaultText": string;
    }
}
declare global {
    interface HTMLNewTodoElement extends Components.NewTodo, HTMLStencilElement {
    }
    var HTMLNewTodoElement: {
        prototype: HTMLNewTodoElement;
        new (): HTMLNewTodoElement;
    };
    interface HTMLElementTagNameMap {
        "new-todo": HTMLNewTodoElement;
    }
}
declare namespace LocalJSX {
    interface NewTodo {
        "defaultText"?: string;
        "onNewTodo"?: (event: CustomEvent<String>) => void;
    }
    interface IntrinsicElements {
        "new-todo": NewTodo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "new-todo": LocalJSX.NewTodo & JSXBase.HTMLAttributes<HTMLNewTodoElement>;
        }
    }
}
